//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlitzFramework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlitzFramework.Resources.Literals", typeof(Literals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedBy.
        /// </summary>
        internal static string CreatedByFieldName {
            get {
                return ResourceManager.GetString("CreatedByFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedOn.
        /// </summary>
        internal static string CreatedOnFieldName {
            get {
                return ResourceManager.GetString("CreatedOnFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeletedOn.
        /// </summary>
        internal static string DeletedOnFieldName {
            get {
                return ResourceManager.GetString("DeletedOnFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete item not found in database.(Id: {0}).
        /// </summary>
        internal static string DeleteItemNotFound {
            get {
                return ResourceManager.GetString("DeleteItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDeleted.
        /// </summary>
        internal static string IsDeletedFieldName {
            get {
                return ResourceManager.GetString("IsDeletedFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error..
        /// </summary>
        internal static string ServerError_Message {
            get {
                return ResourceManager.GetString("ServerError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized user..
        /// </summary>
        internal static string Unauthorized_Message {
            get {
                return ResourceManager.GetString("Unauthorized_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdatedBy.
        /// </summary>
        internal static string UpdatedByFieldName {
            get {
                return ResourceManager.GetString("UpdatedByFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdatedOn.
        /// </summary>
        internal static string UpdatedOnFieldName {
            get {
                return ResourceManager.GetString("UpdatedOnFieldName", resourceCulture);
            }
        }
    }
}
